/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.13.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionSair;
    QAction *actionacton;
    QAction *actionaction_Help;
    QWidget *centralWidget;
    QGroupBox *GrBox_Classificacao;
    QLabel *Lbl_DataIncubacao;
    QDateEdit *Edt_DataIncubacao;
    QLabel *Lbl_Protocolo;
    QLineEdit *Edt_Protocolo;
    QLabel *Lbl_Mercado;
    QComboBox *CmB_Mercado;
    QLabel *Lbl_OrigemMateriaPrima;
    QLabel *Lbl_Setor;
    QLabel *Lbl_AmostraFase;
    QLabel *Lbl_PontoColeta;
    QLineEdit *Edt_PontoColeta;
    QLabel *Lbl_InformacaoComplementar;
    QTextEdit *EdtText_InformacoesComplementares;
    QComboBox *CmB_OrigemMateriaPrima;
    QComboBox *CmB_Setor;
    QComboBox *CmB_AmostraFase;
    QLabel *Lbl_Procedencia;
    QComboBox *CmB_Procedencia;
    QGroupBox *groupBox;
    QPushButton *Btn_Salvar;
    QLabel *label_Obrigatorios;
    QGroupBox *GrBox_Valores;
    QLabel *Lbl_Biogas;
    QLineEdit *Edt_Biogas1;
    QLabel *Lbl_AmostraBiogas1;
    QLineEdit *Edt_Biogas2;
    QLineEdit *Edt_Biogas3;
    QLineEdit *Edt_Metano3;
    QLineEdit *Edt_Metano2;
    QLineEdit *Edt_Metano1;
    QLabel *Lbl_Metano;
    QLineEdit *Edt_ST1;
    QLineEdit *Edt_ST2;
    QLineEdit *Edt_ST3;
    QLabel *Lbl_ST;
    QLineEdit *Edt_SV3;
    QLabel *Lbl_SV1;
    QLineEdit *Edt_SV1;
    QLineEdit *Edt_SV2;
    QLineEdit *Edt_DQO3;
    QLineEdit *Edt_DQO2;
    QLineEdit *Edt_DQO1;
    QLabel *Lbl_DQO;
    QLineEdit *Edt_pH3;
    QLineEdit *Edt_pH1;
    QLineEdit *Edt_pH2;
    QLabel *Lbl_pH;
    QLabel *Lbl_DQO_2;
    QLabel *Lbl_SV1_2;
    QLabel *Lbl_Metano_2;
    QLabel *Lbl_ST_2;
    QLabel *Lbl_Biogas_2;
    QLabel *Lbl_pH_2;
    QLabel *Lbl_Metano_3;
    QLabel *Lbl_SV1_3;
    QLabel *Lbl_DQO_3;
    QLabel *Lbl_ST_3;
    QLabel *Lbl_Biogas_3;
    QLabel *Lbl_pH_3;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QMenuBar *menuBar;
    QMenu *menuArquivo;
    QMenu *menuAjuda;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->setWindowModality(Qt::NonModal);
        MainWindow->resize(763, 722);
        MainWindow->setAutoFillBackground(false);
        MainWindow->setStyleSheet(QString::fromUtf8("QGroupBox {\n"
"    background-color: #e1e1e1;\n"
"}"));
        actionSair = new QAction(MainWindow);
        actionSair->setObjectName(QString::fromUtf8("actionSair"));
        actionacton = new QAction(MainWindow);
        actionacton->setObjectName(QString::fromUtf8("actionacton"));
        actionaction_Help = new QAction(MainWindow);
        actionaction_Help->setObjectName(QString::fromUtf8("actionaction_Help"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        GrBox_Classificacao = new QGroupBox(centralWidget);
        GrBox_Classificacao->setObjectName(QString::fromUtf8("GrBox_Classificacao"));
        GrBox_Classificacao->setGeometry(QRect(1, 1, 361, 621));
        GrBox_Classificacao->setAutoFillBackground(false);
        Lbl_DataIncubacao = new QLabel(GrBox_Classificacao);
        Lbl_DataIncubacao->setObjectName(QString::fromUtf8("Lbl_DataIncubacao"));
        Lbl_DataIncubacao->setGeometry(QRect(10, 10, 151, 17));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        Lbl_DataIncubacao->setFont(font);
        Edt_DataIncubacao = new QDateEdit(GrBox_Classificacao);
        Edt_DataIncubacao->setObjectName(QString::fromUtf8("Edt_DataIncubacao"));
        Edt_DataIncubacao->setGeometry(QRect(10, 30, 110, 27));
        Edt_DataIncubacao->setDateTime(QDateTime(QDate(2019, 1, 1), QTime(0, 0, 0)));
        Edt_DataIncubacao->setCalendarPopup(true);
        Edt_DataIncubacao->setTimeSpec(Qt::TimeZone);
        Lbl_Protocolo = new QLabel(GrBox_Classificacao);
        Lbl_Protocolo->setObjectName(QString::fromUtf8("Lbl_Protocolo"));
        Lbl_Protocolo->setGeometry(QRect(10, 70, 91, 17));
        Lbl_Protocolo->setFont(font);
        Edt_Protocolo = new QLineEdit(GrBox_Classificacao);
        Edt_Protocolo->setObjectName(QString::fromUtf8("Edt_Protocolo"));
        Edt_Protocolo->setGeometry(QRect(10, 90, 151, 31));
        Edt_Protocolo->setMaxLength(15);
        Lbl_Mercado = new QLabel(GrBox_Classificacao);
        Lbl_Mercado->setObjectName(QString::fromUtf8("Lbl_Mercado"));
        Lbl_Mercado->setGeometry(QRect(10, 200, 111, 17));
        Lbl_Mercado->setFont(font);
        CmB_Mercado = new QComboBox(GrBox_Classificacao);
        CmB_Mercado->addItem(QString());
        CmB_Mercado->addItem(QString());
        CmB_Mercado->addItem(QString());
        CmB_Mercado->addItem(QString());
        CmB_Mercado->addItem(QString());
        CmB_Mercado->addItem(QString());
        CmB_Mercado->setObjectName(QString::fromUtf8("CmB_Mercado"));
        CmB_Mercado->setGeometry(QRect(10, 220, 171, 25));
        Lbl_OrigemMateriaPrima = new QLabel(GrBox_Classificacao);
        Lbl_OrigemMateriaPrima->setObjectName(QString::fromUtf8("Lbl_OrigemMateriaPrima"));
        Lbl_OrigemMateriaPrima->setGeometry(QRect(10, 260, 191, 17));
        Lbl_OrigemMateriaPrima->setFont(font);
        Lbl_Setor = new QLabel(GrBox_Classificacao);
        Lbl_Setor->setObjectName(QString::fromUtf8("Lbl_Setor"));
        Lbl_Setor->setGeometry(QRect(10, 320, 41, 17));
        Lbl_Setor->setFont(font);
        Lbl_AmostraFase = new QLabel(GrBox_Classificacao);
        Lbl_AmostraFase->setObjectName(QString::fromUtf8("Lbl_AmostraFase"));
        Lbl_AmostraFase->setGeometry(QRect(10, 380, 111, 17));
        Lbl_AmostraFase->setFont(font);
        Lbl_PontoColeta = new QLabel(GrBox_Classificacao);
        Lbl_PontoColeta->setObjectName(QString::fromUtf8("Lbl_PontoColeta"));
        Lbl_PontoColeta->setGeometry(QRect(10, 440, 151, 17));
        Lbl_PontoColeta->setFont(font);
        Edt_PontoColeta = new QLineEdit(GrBox_Classificacao);
        Edt_PontoColeta->setObjectName(QString::fromUtf8("Edt_PontoColeta"));
        Edt_PontoColeta->setGeometry(QRect(10, 460, 341, 29));
        Edt_PontoColeta->setMaxLength(100);
        Lbl_InformacaoComplementar = new QLabel(GrBox_Classificacao);
        Lbl_InformacaoComplementar->setObjectName(QString::fromUtf8("Lbl_InformacaoComplementar"));
        Lbl_InformacaoComplementar->setGeometry(QRect(10, 510, 221, 17));
        Lbl_InformacaoComplementar->setFont(font);
        EdtText_InformacoesComplementares = new QTextEdit(GrBox_Classificacao);
        EdtText_InformacoesComplementares->setObjectName(QString::fromUtf8("EdtText_InformacoesComplementares"));
        EdtText_InformacoesComplementares->setGeometry(QRect(10, 530, 341, 64));
        EdtText_InformacoesComplementares->setAutoFillBackground(false);
        EdtText_InformacoesComplementares->setAcceptRichText(true);
        CmB_OrigemMateriaPrima = new QComboBox(GrBox_Classificacao);
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->addItem(QString());
        CmB_OrigemMateriaPrima->setObjectName(QString::fromUtf8("CmB_OrigemMateriaPrima"));
        CmB_OrigemMateriaPrima->setGeometry(QRect(10, 280, 261, 25));
        CmB_Setor = new QComboBox(GrBox_Classificacao);
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->addItem(QString());
        CmB_Setor->setObjectName(QString::fromUtf8("CmB_Setor"));
        CmB_Setor->setGeometry(QRect(10, 340, 261, 25));
        CmB_AmostraFase = new QComboBox(GrBox_Classificacao);
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->addItem(QString());
        CmB_AmostraFase->setObjectName(QString::fromUtf8("CmB_AmostraFase"));
        CmB_AmostraFase->setGeometry(QRect(10, 400, 261, 25));
        Lbl_Procedencia = new QLabel(GrBox_Classificacao);
        Lbl_Procedencia->setObjectName(QString::fromUtf8("Lbl_Procedencia"));
        Lbl_Procedencia->setGeometry(QRect(10, 140, 111, 10));
        Lbl_Procedencia->setFont(font);
        CmB_Procedencia = new QComboBox(GrBox_Classificacao);
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->addItem(QString());
        CmB_Procedencia->setObjectName(QString::fromUtf8("CmB_Procedencia"));
        CmB_Procedencia->setGeometry(QRect(10, 160, 261, 25));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(1, 630, 761, 51));
        Btn_Salvar = new QPushButton(groupBox);
        Btn_Salvar->setObjectName(QString::fromUtf8("Btn_Salvar"));
        Btn_Salvar->setGeometry(QRect(660, 10, 87, 29));
        label_Obrigatorios = new QLabel(groupBox);
        label_Obrigatorios->setObjectName(QString::fromUtf8("label_Obrigatorios"));
        label_Obrigatorios->setGeometry(QRect(20, 20, 121, 16));
        GrBox_Valores = new QGroupBox(centralWidget);
        GrBox_Valores->setObjectName(QString::fromUtf8("GrBox_Valores"));
        GrBox_Valores->setGeometry(QRect(370, 0, 391, 621));
        GrBox_Valores->setAutoFillBackground(false);
        Lbl_Biogas = new QLabel(GrBox_Valores);
        Lbl_Biogas->setObjectName(QString::fromUtf8("Lbl_Biogas"));
        Lbl_Biogas->setGeometry(QRect(10, 40, 151, 17));
        Lbl_Biogas->setFont(font);
        Edt_Biogas1 = new QLineEdit(GrBox_Valores);
        Edt_Biogas1->setObjectName(QString::fromUtf8("Edt_Biogas1"));
        Edt_Biogas1->setGeometry(QRect(10, 60, 161, 21));
        Edt_Biogas1->setMaxLength(6);
        Lbl_AmostraBiogas1 = new QLabel(GrBox_Valores);
        Lbl_AmostraBiogas1->setObjectName(QString::fromUtf8("Lbl_AmostraBiogas1"));
        Lbl_AmostraBiogas1->setGeometry(QRect(250, 10, 61, 17));
        Lbl_AmostraBiogas1->setFont(font);
        Edt_Biogas2 = new QLineEdit(GrBox_Valores);
        Edt_Biogas2->setObjectName(QString::fromUtf8("Edt_Biogas2"));
        Edt_Biogas2->setEnabled(true);
        Edt_Biogas2->setGeometry(QRect(10, 110, 161, 21));
        Edt_Biogas2->setMaxLength(6);
        Edt_Biogas3 = new QLineEdit(GrBox_Valores);
        Edt_Biogas3->setObjectName(QString::fromUtf8("Edt_Biogas3"));
        Edt_Biogas3->setEnabled(true);
        Edt_Biogas3->setGeometry(QRect(10, 160, 161, 21));
        Edt_Biogas3->setMaxLength(6);
        Edt_Metano3 = new QLineEdit(GrBox_Valores);
        Edt_Metano3->setObjectName(QString::fromUtf8("Edt_Metano3"));
        Edt_Metano3->setEnabled(true);
        Edt_Metano3->setGeometry(QRect(10, 330, 161, 21));
        Edt_Metano3->setMaxLength(6);
        Edt_Metano2 = new QLineEdit(GrBox_Valores);
        Edt_Metano2->setObjectName(QString::fromUtf8("Edt_Metano2"));
        Edt_Metano2->setEnabled(true);
        Edt_Metano2->setGeometry(QRect(10, 280, 161, 21));
        Edt_Metano2->setMaxLength(6);
        Edt_Metano1 = new QLineEdit(GrBox_Valores);
        Edt_Metano1->setObjectName(QString::fromUtf8("Edt_Metano1"));
        Edt_Metano1->setGeometry(QRect(10, 230, 161, 21));
        Edt_Metano1->setMaxLength(6);
        Lbl_Metano = new QLabel(GrBox_Valores);
        Lbl_Metano->setObjectName(QString::fromUtf8("Lbl_Metano"));
        Lbl_Metano->setGeometry(QRect(10, 210, 161, 17));
        Lbl_Metano->setFont(font);
        Edt_ST1 = new QLineEdit(GrBox_Valores);
        Edt_ST1->setObjectName(QString::fromUtf8("Edt_ST1"));
        Edt_ST1->setGeometry(QRect(10, 400, 161, 21));
        Edt_ST1->setMaxLength(6);
        Edt_ST2 = new QLineEdit(GrBox_Valores);
        Edt_ST2->setObjectName(QString::fromUtf8("Edt_ST2"));
        Edt_ST2->setEnabled(true);
        Edt_ST2->setGeometry(QRect(10, 450, 161, 21));
        Edt_ST2->setMaxLength(6);
        Edt_ST3 = new QLineEdit(GrBox_Valores);
        Edt_ST3->setObjectName(QString::fromUtf8("Edt_ST3"));
        Edt_ST3->setEnabled(true);
        Edt_ST3->setGeometry(QRect(10, 500, 161, 21));
        Edt_ST3->setMaxLength(6);
        Lbl_ST = new QLabel(GrBox_Valores);
        Lbl_ST->setObjectName(QString::fromUtf8("Lbl_ST"));
        Lbl_ST->setGeometry(QRect(10, 380, 151, 17));
        Lbl_ST->setFont(font);
        Edt_SV3 = new QLineEdit(GrBox_Valores);
        Edt_SV3->setObjectName(QString::fromUtf8("Edt_SV3"));
        Edt_SV3->setEnabled(true);
        Edt_SV3->setGeometry(QRect(210, 160, 161, 21));
        Edt_SV3->setMaxLength(6);
        Lbl_SV1 = new QLabel(GrBox_Valores);
        Lbl_SV1->setObjectName(QString::fromUtf8("Lbl_SV1"));
        Lbl_SV1->setGeometry(QRect(210, 40, 151, 17));
        Lbl_SV1->setFont(font);
        Edt_SV1 = new QLineEdit(GrBox_Valores);
        Edt_SV1->setObjectName(QString::fromUtf8("Edt_SV1"));
        Edt_SV1->setGeometry(QRect(210, 60, 161, 21));
        Edt_SV1->setMaxLength(6);
        Edt_SV2 = new QLineEdit(GrBox_Valores);
        Edt_SV2->setObjectName(QString::fromUtf8("Edt_SV2"));
        Edt_SV2->setEnabled(true);
        Edt_SV2->setGeometry(QRect(210, 110, 161, 21));
        Edt_SV2->setMaxLength(6);
        Edt_DQO3 = new QLineEdit(GrBox_Valores);
        Edt_DQO3->setObjectName(QString::fromUtf8("Edt_DQO3"));
        Edt_DQO3->setEnabled(true);
        Edt_DQO3->setGeometry(QRect(210, 330, 161, 21));
        Edt_DQO3->setMaxLength(6);
        Edt_DQO2 = new QLineEdit(GrBox_Valores);
        Edt_DQO2->setObjectName(QString::fromUtf8("Edt_DQO2"));
        Edt_DQO2->setEnabled(true);
        Edt_DQO2->setGeometry(QRect(210, 280, 161, 21));
        Edt_DQO2->setMaxLength(6);
        Edt_DQO1 = new QLineEdit(GrBox_Valores);
        Edt_DQO1->setObjectName(QString::fromUtf8("Edt_DQO1"));
        Edt_DQO1->setGeometry(QRect(210, 230, 161, 21));
        Edt_DQO1->setMaxLength(6);
        Lbl_DQO = new QLabel(GrBox_Valores);
        Lbl_DQO->setObjectName(QString::fromUtf8("Lbl_DQO"));
        Lbl_DQO->setGeometry(QRect(210, 210, 151, 17));
        Lbl_DQO->setFont(font);
        Edt_pH3 = new QLineEdit(GrBox_Valores);
        Edt_pH3->setObjectName(QString::fromUtf8("Edt_pH3"));
        Edt_pH3->setEnabled(true);
        Edt_pH3->setGeometry(QRect(210, 500, 161, 21));
        Edt_pH3->setMaxLength(6);
        Edt_pH1 = new QLineEdit(GrBox_Valores);
        Edt_pH1->setObjectName(QString::fromUtf8("Edt_pH1"));
        Edt_pH1->setGeometry(QRect(210, 400, 161, 21));
        Edt_pH1->setMaxLength(6);
        Edt_pH2 = new QLineEdit(GrBox_Valores);
        Edt_pH2->setObjectName(QString::fromUtf8("Edt_pH2"));
        Edt_pH2->setEnabled(true);
        Edt_pH2->setGeometry(QRect(210, 450, 161, 21));
        Edt_pH2->setMaxLength(6);
        Lbl_pH = new QLabel(GrBox_Valores);
        Lbl_pH->setObjectName(QString::fromUtf8("Lbl_pH"));
        Lbl_pH->setGeometry(QRect(210, 380, 151, 17));
        Lbl_pH->setFont(font);
        Lbl_DQO_2 = new QLabel(GrBox_Valores);
        Lbl_DQO_2->setObjectName(QString::fromUtf8("Lbl_DQO_2"));
        Lbl_DQO_2->setGeometry(QRect(210, 260, 151, 17));
        Lbl_DQO_2->setFont(font);
        Lbl_SV1_2 = new QLabel(GrBox_Valores);
        Lbl_SV1_2->setObjectName(QString::fromUtf8("Lbl_SV1_2"));
        Lbl_SV1_2->setGeometry(QRect(210, 90, 151, 17));
        Lbl_SV1_2->setFont(font);
        Lbl_Metano_2 = new QLabel(GrBox_Valores);
        Lbl_Metano_2->setObjectName(QString::fromUtf8("Lbl_Metano_2"));
        Lbl_Metano_2->setGeometry(QRect(10, 260, 161, 17));
        Lbl_Metano_2->setFont(font);
        Lbl_ST_2 = new QLabel(GrBox_Valores);
        Lbl_ST_2->setObjectName(QString::fromUtf8("Lbl_ST_2"));
        Lbl_ST_2->setGeometry(QRect(10, 430, 151, 17));
        Lbl_ST_2->setFont(font);
        Lbl_Biogas_2 = new QLabel(GrBox_Valores);
        Lbl_Biogas_2->setObjectName(QString::fromUtf8("Lbl_Biogas_2"));
        Lbl_Biogas_2->setGeometry(QRect(10, 90, 151, 17));
        Lbl_Biogas_2->setFont(font);
        Lbl_pH_2 = new QLabel(GrBox_Valores);
        Lbl_pH_2->setObjectName(QString::fromUtf8("Lbl_pH_2"));
        Lbl_pH_2->setGeometry(QRect(210, 430, 151, 17));
        Lbl_pH_2->setFont(font);
        Lbl_Metano_3 = new QLabel(GrBox_Valores);
        Lbl_Metano_3->setObjectName(QString::fromUtf8("Lbl_Metano_3"));
        Lbl_Metano_3->setGeometry(QRect(10, 310, 161, 17));
        Lbl_Metano_3->setFont(font);
        Lbl_SV1_3 = new QLabel(GrBox_Valores);
        Lbl_SV1_3->setObjectName(QString::fromUtf8("Lbl_SV1_3"));
        Lbl_SV1_3->setGeometry(QRect(210, 140, 151, 17));
        Lbl_SV1_3->setFont(font);
        Lbl_DQO_3 = new QLabel(GrBox_Valores);
        Lbl_DQO_3->setObjectName(QString::fromUtf8("Lbl_DQO_3"));
        Lbl_DQO_3->setGeometry(QRect(210, 310, 151, 17));
        Lbl_DQO_3->setFont(font);
        Lbl_ST_3 = new QLabel(GrBox_Valores);
        Lbl_ST_3->setObjectName(QString::fromUtf8("Lbl_ST_3"));
        Lbl_ST_3->setGeometry(QRect(10, 480, 151, 17));
        Lbl_ST_3->setFont(font);
        Lbl_Biogas_3 = new QLabel(GrBox_Valores);
        Lbl_Biogas_3->setObjectName(QString::fromUtf8("Lbl_Biogas_3"));
        Lbl_Biogas_3->setGeometry(QRect(10, 140, 151, 17));
        Lbl_Biogas_3->setFont(font);
        Lbl_pH_3 = new QLabel(GrBox_Valores);
        Lbl_pH_3->setObjectName(QString::fromUtf8("Lbl_pH_3"));
        Lbl_pH_3->setGeometry(QRect(210, 480, 151, 17));
        Lbl_pH_3->setFont(font);
        line = new QFrame(GrBox_Valores);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(180, 40, 20, 581));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(GrBox_Valores);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(10, 190, 161, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(GrBox_Valores);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(10, 360, 161, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(GrBox_Valores);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(210, 190, 161, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(GrBox_Valores);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(210, 360, 161, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 763, 21));
        menuArquivo = new QMenu(menuBar);
        menuArquivo->setObjectName(QString::fromUtf8("menuArquivo"));
        menuAjuda = new QMenu(menuBar);
        menuAjuda->setObjectName(QString::fromUtf8("menuAjuda"));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);
        QWidget::setTabOrder(Edt_DataIncubacao, Edt_Protocolo);
        QWidget::setTabOrder(Edt_Protocolo, CmB_Procedencia);
        QWidget::setTabOrder(CmB_Procedencia, CmB_Mercado);
        QWidget::setTabOrder(CmB_Mercado, CmB_OrigemMateriaPrima);
        QWidget::setTabOrder(CmB_OrigemMateriaPrima, CmB_Setor);
        QWidget::setTabOrder(CmB_Setor, CmB_AmostraFase);
        QWidget::setTabOrder(CmB_AmostraFase, Edt_PontoColeta);
        QWidget::setTabOrder(Edt_PontoColeta, EdtText_InformacoesComplementares);
        QWidget::setTabOrder(EdtText_InformacoesComplementares, Edt_Biogas1);
        QWidget::setTabOrder(Edt_Biogas1, Edt_Biogas2);
        QWidget::setTabOrder(Edt_Biogas2, Edt_Biogas3);
        QWidget::setTabOrder(Edt_Biogas3, Edt_Metano1);
        QWidget::setTabOrder(Edt_Metano1, Edt_Metano2);
        QWidget::setTabOrder(Edt_Metano2, Edt_Metano3);
        QWidget::setTabOrder(Edt_Metano3, Edt_ST1);
        QWidget::setTabOrder(Edt_ST1, Edt_ST2);
        QWidget::setTabOrder(Edt_ST2, Edt_ST3);
        QWidget::setTabOrder(Edt_ST3, Edt_SV1);
        QWidget::setTabOrder(Edt_SV1, Edt_SV2);
        QWidget::setTabOrder(Edt_SV2, Edt_SV3);
        QWidget::setTabOrder(Edt_SV3, Edt_DQO1);
        QWidget::setTabOrder(Edt_DQO1, Edt_DQO2);
        QWidget::setTabOrder(Edt_DQO2, Edt_DQO3);
        QWidget::setTabOrder(Edt_DQO3, Edt_pH1);
        QWidget::setTabOrder(Edt_pH1, Edt_pH2);
        QWidget::setTabOrder(Edt_pH2, Edt_pH3);
        QWidget::setTabOrder(Edt_pH3, Btn_Salvar);

        menuBar->addAction(menuArquivo->menuAction());
        menuBar->addAction(menuAjuda->menuAction());
        menuArquivo->addAction(actionSair);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "CIBLAB - Cadastro de Informa\303\247\303\265es do Laborat\303\263rio de Biog\303\241s", nullptr));
        actionSair->setText(QCoreApplication::translate("MainWindow", "Sair", nullptr));
        actionacton->setText(QCoreApplication::translate("MainWindow", "acton", nullptr));
        actionaction_Help->setText(QCoreApplication::translate("MainWindow", "action_Help", nullptr));
        GrBox_Classificacao->setTitle(QString());
        Lbl_DataIncubacao->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Data de incuba\303\247\303\243o*</p></body></html>", nullptr));
        Lbl_Protocolo->setText(QCoreApplication::translate("MainWindow", "Protocolo*", nullptr));
        Edt_Protocolo->setInputMask(QString());
        Edt_Protocolo->setText(QString());
        Edt_Protocolo->setPlaceholderText(QCoreApplication::translate("MainWindow", "IN-18/03/19", nullptr));
        Lbl_Mercado->setText(QCoreApplication::translate("MainWindow", "Mercado*", nullptr));
        CmB_Mercado->setItemText(0, QCoreApplication::translate("MainWindow", "--Selecione--", nullptr));
        CmB_Mercado->setItemText(1, QCoreApplication::translate("MainWindow", "AgroInd\303\272stria", nullptr));
        CmB_Mercado->setItemText(2, QCoreApplication::translate("MainWindow", "Cultura Energ\303\251tica", nullptr));
        CmB_Mercado->setItemText(3, QCoreApplication::translate("MainWindow", "Garantia de Qualidade", nullptr));
        CmB_Mercado->setItemText(4, QCoreApplication::translate("MainWindow", "Ind\303\272stria", nullptr));
        CmB_Mercado->setItemText(5, QCoreApplication::translate("MainWindow", "Res\303\255duo Urbano", nullptr));

        Lbl_OrigemMateriaPrima->setText(QCoreApplication::translate("MainWindow", "Origem da Mat\303\251ria Prima*", nullptr));
        Lbl_Setor->setText(QCoreApplication::translate("MainWindow", "Setor*", nullptr));
        Lbl_AmostraFase->setText(QCoreApplication::translate("MainWindow", "Amostra/fase*", nullptr));
        Lbl_PontoColeta->setText(QCoreApplication::translate("MainWindow", "Ponto de Coleta", nullptr));
        Edt_PontoColeta->setText(QString());
        Edt_PontoColeta->setPlaceholderText(QCoreApplication::translate("MainWindow", "Informe o ponto de coleta", nullptr));
        Lbl_InformacaoComplementar->setText(QCoreApplication::translate("MainWindow", "Informa\303\247\303\265es Complementares", nullptr));
        EdtText_InformacoesComplementares->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", nullptr));
        EdtText_InformacoesComplementares->setPlaceholderText(QString());
        CmB_OrigemMateriaPrima->setItemText(0, QCoreApplication::translate("MainWindow", "--Selecione--", nullptr));
        CmB_OrigemMateriaPrima->setItemText(1, QCoreApplication::translate("MainWindow", "Codigest\303\243o", nullptr));
        CmB_OrigemMateriaPrima->setItemText(2, QCoreApplication::translate("MainWindow", "Cultivo Energ\303\251tico", nullptr));
        CmB_OrigemMateriaPrima->setItemText(3, QCoreApplication::translate("MainWindow", "Padr\303\243o", nullptr));
        CmB_OrigemMateriaPrima->setItemText(4, QCoreApplication::translate("MainWindow", "Res\303\255duo de Tratamento de Esgoto", nullptr));
        CmB_OrigemMateriaPrima->setItemText(5, QCoreApplication::translate("MainWindow", "Res\303\255duos Alimentares", nullptr));
        CmB_OrigemMateriaPrima->setItemText(6, QCoreApplication::translate("MainWindow", "Res\303\255duo da Ind\303\272stria Agropecu\303\241ria", nullptr));
        CmB_OrigemMateriaPrima->setItemText(7, QCoreApplication::translate("MainWindow", "Res\303\255duo da Industria de Biocombustiveis", nullptr));
        CmB_OrigemMateriaPrima->setItemText(8, QCoreApplication::translate("MainWindow", "Res\303\255duos da Produ\303\247\303\243o de A\303\247\303\272car, Am\303\255do e Produtos Secund\303\241rios", nullptr));
        CmB_OrigemMateriaPrima->setItemText(9, QCoreApplication::translate("MainWindow", "Res\303\255duos da Produ\303\247\303\243o de \303\223leo", nullptr));
        CmB_OrigemMateriaPrima->setItemText(10, QCoreApplication::translate("MainWindow", "Res\303\255duos de Matadouro e Restos de Animais", nullptr));
        CmB_OrigemMateriaPrima->setItemText(11, QCoreApplication::translate("MainWindow", "Res\303\255duos de Pecu\303\241ria", nullptr));
        CmB_OrigemMateriaPrima->setItemText(12, QCoreApplication::translate("MainWindow", "Res\303\255duos Diversos da Ind\303\272stria de Alimentos", nullptr));
        CmB_OrigemMateriaPrima->setItemText(13, QCoreApplication::translate("MainWindow", "Res\303\255duos Industriais", nullptr));

        CmB_Setor->setItemText(0, QCoreApplication::translate("MainWindow", "--Selecione--", nullptr));
        CmB_Setor->setItemText(1, QCoreApplication::translate("MainWindow", "Abatedouro de Aves", nullptr));
        CmB_Setor->setItemText(2, QCoreApplication::translate("MainWindow", "Alga", nullptr));
        CmB_Setor->setItemText(3, QCoreApplication::translate("MainWindow", "Alho", nullptr));
        CmB_Setor->setItemText(4, QCoreApplication::translate("MainWindow", "Amidonaria", nullptr));
        CmB_Setor->setItemText(5, QCoreApplication::translate("MainWindow", "Avicultura", nullptr));
        CmB_Setor->setItemText(6, QCoreApplication::translate("MainWindow", "Biomassa Vegetal", nullptr));
        CmB_Setor->setItemText(7, QCoreApplication::translate("MainWindow", "Bovinocultura", nullptr));
        CmB_Setor->setItemText(8, QCoreApplication::translate("MainWindow", "Carne", nullptr));
        CmB_Setor->setItemText(9, QCoreApplication::translate("MainWindow", "Cebola", nullptr));
        CmB_Setor->setItemText(10, QCoreApplication::translate("MainWindow", "Efluente Industrial", nullptr));
        CmB_Setor->setItemText(11, QCoreApplication::translate("MainWindow", "Esgoto Dom\303\251stico", nullptr));
        CmB_Setor->setItemText(12, QCoreApplication::translate("MainWindow", "Feij\303\243o", nullptr));
        CmB_Setor->setItemText(13, QCoreApplication::translate("MainWindow", "Gelatina", nullptr));
        CmB_Setor->setItemText(14, QCoreApplication::translate("MainWindow", "Glicerol", nullptr));
        CmB_Setor->setItemText(15, QCoreApplication::translate("MainWindow", "Gordura", nullptr));
        CmB_Setor->setItemText(16, QCoreApplication::translate("MainWindow", "Ind\303\272stria de Beneficiamento de Arroz", nullptr));
        CmB_Setor->setItemText(17, QCoreApplication::translate("MainWindow", "Ind\303\272stria Sucroalcoleira", nullptr));
        CmB_Setor->setItemText(18, QCoreApplication::translate("MainWindow", "Latic\303\255neio", nullptr));
        CmB_Setor->setItemText(19, QCoreApplication::translate("MainWindow", "Lodo", nullptr));
        CmB_Setor->setItemText(20, QCoreApplication::translate("MainWindow", "Macr\303\263fita", nullptr));
        CmB_Setor->setItemText(21, QCoreApplication::translate("MainWindow", "Maravalha", nullptr));
        CmB_Setor->setItemText(22, QCoreApplication::translate("MainWindow", "\303\223leo Vegetal", nullptr));
        CmB_Setor->setItemText(23, QCoreApplication::translate("MainWindow", "Ovinoultura", nullptr));
        CmB_Setor->setItemText(24, QCoreApplication::translate("MainWindow", "Padr\303\243o Positivo", nullptr));
        CmB_Setor->setItemText(25, QCoreApplication::translate("MainWindow", "Ra\303\247\303\243o Animal", nullptr));
        CmB_Setor->setItemText(26, QCoreApplication::translate("MainWindow", "Res\303\255duo da Industria de Papel e Celulose", nullptr));
        CmB_Setor->setItemText(27, QCoreApplication::translate("MainWindow", "Res\303\255duo de Cigarro", nullptr));
        CmB_Setor->setItemText(28, QCoreApplication::translate("MainWindow", "Res\303\255duo de Peneira de Gr\303\243os", nullptr));
        CmB_Setor->setItemText(29, QCoreApplication::translate("MainWindow", "Res\303\255duo de Pescado", nullptr));
        CmB_Setor->setItemText(30, QCoreApplication::translate("MainWindow", "Res\303\255duo de S\303\263lido Org\303\242nico", nullptr));
        CmB_Setor->setItemText(31, QCoreApplication::translate("MainWindow", "Silagem", nullptr));
        CmB_Setor->setItemText(32, QCoreApplication::translate("MainWindow", "Suinocultura", nullptr));
        CmB_Setor->setItemText(33, QCoreApplication::translate("MainWindow", "Ind\303\272stria de suco", nullptr));

        CmB_AmostraFase->setItemText(0, QCoreApplication::translate("MainWindow", "--Selecione--", nullptr));
        CmB_AmostraFase->setItemText(1, QCoreApplication::translate("MainWindow", "\303\201gua Residual", nullptr));
        CmB_AmostraFase->setItemText(2, QCoreApplication::translate("MainWindow", "Algas Decantadas", nullptr));
        CmB_AmostraFase->setItemText(3, QCoreApplication::translate("MainWindow", "Algas Floculadas", nullptr));
        CmB_AmostraFase->setItemText(4, QCoreApplication::translate("MainWindow", "Alho", nullptr));
        CmB_AmostraFase->setItemText(5, QCoreApplication::translate("MainWindow", "Amido de Mandioca", nullptr));
        CmB_AmostraFase->setItemText(6, QCoreApplication::translate("MainWindow", "Amostra S\303\263lida", nullptr));
        CmB_AmostraFase->setItemText(7, QCoreApplication::translate("MainWindow", "Amostra Suco", nullptr));
        CmB_AmostraFase->setItemText(8, QCoreApplication::translate("MainWindow", "Armazenamento", nullptr));
        CmB_AmostraFase->setItemText(9, QCoreApplication::translate("MainWindow", "Aves Poedeiras", nullptr));
        CmB_AmostraFase->setItemText(10, QCoreApplication::translate("MainWindow", "Baga\303\247o de Cana", nullptr));
        CmB_AmostraFase->setItemText(11, QCoreApplication::translate("MainWindow", "Bolacha + Massa de Recheio", nullptr));
        CmB_AmostraFase->setItemText(12, QCoreApplication::translate("MainWindow", "Bovino + Aves Poedeiras", nullptr));
        CmB_AmostraFase->setItemText(13, QCoreApplication::translate("MainWindow", "Bovino + Su\303\255no", nullptr));
        CmB_AmostraFase->setItemText(14, QCoreApplication::translate("MainWindow", "Caf\303\251", nullptr));
        CmB_AmostraFase->setItemText(15, QCoreApplication::translate("MainWindow", "Cama de Aves", nullptr));
        CmB_AmostraFase->setItemText(16, QCoreApplication::translate("MainWindow", "Cama de Bovinos", nullptr));
        CmB_AmostraFase->setItemText(17, QCoreApplication::translate("MainWindow", "Cama de Matrizeiro", nullptr));
        CmB_AmostraFase->setItemText(18, QCoreApplication::translate("MainWindow", "Cana Energia", nullptr));
        CmB_AmostraFase->setItemText(19, QCoreApplication::translate("MainWindow", "Capim Elefante", nullptr));
        CmB_AmostraFase->setItemText(20, QCoreApplication::translate("MainWindow", "Carne", nullptr));
        CmB_AmostraFase->setItemText(21, QCoreApplication::translate("MainWindow", "Casca de Arroz", nullptr));
        CmB_AmostraFase->setItemText(22, QCoreApplication::translate("MainWindow", "Cebola", nullptr));
        CmB_AmostraFase->setItemText(23, QCoreApplication::translate("MainWindow", "Celulose Cristalina", nullptr));
        CmB_AmostraFase->setItemText(24, QCoreApplication::translate("MainWindow", "Ciclo Completo", nullptr));
        CmB_AmostraFase->setItemText(25, QCoreApplication::translate("MainWindow", "Chiorella", nullptr));
        CmB_AmostraFase->setItemText(26, QCoreApplication::translate("MainWindow", "Coco verde", nullptr));
        CmB_AmostraFase->setItemText(27, QCoreApplication::translate("MainWindow", "Compostagem", nullptr));
        CmB_AmostraFase->setItemText(28, QCoreApplication::translate("MainWindow", "Corteza", nullptr));
        CmB_AmostraFase->setItemText(29, QCoreApplication::translate("MainWindow", "Dejeto bovino", nullptr));
        CmB_AmostraFase->setItemText(30, QCoreApplication::translate("MainWindow", "Dejeto de Salm\303\243o", nullptr));
        CmB_AmostraFase->setItemText(31, QCoreApplication::translate("MainWindow", "Creche", nullptr));
        CmB_AmostraFase->setItemText(32, QCoreApplication::translate("MainWindow", "Dejeto de Aves + Bovino de Corte", nullptr));
        CmB_AmostraFase->setItemText(33, QCoreApplication::translate("MainWindow", "Dejeto Ovino", nullptr));
        CmB_AmostraFase->setItemText(34, QCoreApplication::translate("MainWindow", "Dejeto de Su\303\255no", nullptr));
        CmB_AmostraFase->setItemText(35, QCoreApplication::translate("MainWindow", "Efluentes da Agroind\303\272stria", nullptr));
        CmB_AmostraFase->setItemText(36, QCoreApplication::translate("MainWindow", "Efluente Bruto", nullptr));
        CmB_AmostraFase->setItemText(37, QCoreApplication::translate("MainWindow", "Efluente Industrial", nullptr));
        CmB_AmostraFase->setItemText(38, QCoreApplication::translate("MainWindow", "Efluente L\303\255quido", nullptr));
        CmB_AmostraFase->setItemText(39, QCoreApplication::translate("MainWindow", "Esgoto Dom\303\251stico", nullptr));
        CmB_AmostraFase->setItemText(40, QCoreApplication::translate("MainWindow", "Feij\303\243o Preto Cru", nullptr));
        CmB_AmostraFase->setItemText(41, QCoreApplication::translate("MainWindow", "Finos de Madeira", nullptr));
        CmB_AmostraFase->setItemText(42, QCoreApplication::translate("MainWindow", "Folhas de Citronela", nullptr));
        CmB_AmostraFase->setItemText(43, QCoreApplication::translate("MainWindow", "Fra\303\247\303\243o Org\303\242nica RSU", nullptr));
        CmB_AmostraFase->setItemText(44, QCoreApplication::translate("MainWindow", "Gelatina", nullptr));
        CmB_AmostraFase->setItemText(45, QCoreApplication::translate("MainWindow", "Gordura Animal", nullptr));
        CmB_AmostraFase->setItemText(46, QCoreApplication::translate("MainWindow", "Grama", nullptr));
        CmB_AmostraFase->setItemText(47, QCoreApplication::translate("MainWindow", "Lodo", nullptr));
        CmB_AmostraFase->setItemText(48, QCoreApplication::translate("MainWindow", "Macr\303\263fita", nullptr));
        CmB_AmostraFase->setItemText(49, QCoreApplication::translate("MainWindow", "Maravalha com Urina de Rato", nullptr));
        CmB_AmostraFase->setItemText(50, QCoreApplication::translate("MainWindow", "Massa de Mandioca", nullptr));
        CmB_AmostraFase->setItemText(51, QCoreApplication::translate("MainWindow", "Matrizeiro", nullptr));
        CmB_AmostraFase->setItemText(52, QCoreApplication::translate("MainWindow", "Mistura Homogenizada", nullptr));
        CmB_AmostraFase->setItemText(53, QCoreApplication::translate("MainWindow", "Mix", nullptr));
        CmB_AmostraFase->setItemText(54, QCoreApplication::translate("MainWindow", "\303\223leo", nullptr));
        CmB_AmostraFase->setItemText(55, QCoreApplication::translate("MainWindow", "Palha Cultivo Cana", nullptr));
        CmB_AmostraFase->setItemText(56, QCoreApplication::translate("MainWindow", "Visceras de Peixe", nullptr));
        CmB_AmostraFase->setItemText(57, QCoreApplication::translate("MainWindow", "Pistia Stratiolis", nullptr));
        CmB_AmostraFase->setItemText(58, QCoreApplication::translate("MainWindow", "Ra\303\247\303\243o Animal", nullptr));
        CmB_AmostraFase->setItemText(59, QCoreApplication::translate("MainWindow", "Res\303\255duo", nullptr));
        CmB_AmostraFase->setItemText(60, QCoreApplication::translate("MainWindow", "Res\303\255duo de Cigarro", nullptr));
        CmB_AmostraFase->setItemText(61, QCoreApplication::translate("MainWindow", "Res\303\255duo de Glicerol", nullptr));
        CmB_AmostraFase->setItemText(62, QCoreApplication::translate("MainWindow", "Res\303\255duo de Limpeza do Secador de Arroz", nullptr));
        CmB_AmostraFase->setItemText(63, QCoreApplication::translate("MainWindow", "Res\303\255duo de Restaurante", nullptr));
        CmB_AmostraFase->setItemText(64, QCoreApplication::translate("MainWindow", "Res\303\255duo de Secagem de Arroz", nullptr));
        CmB_AmostraFase->setItemText(65, QCoreApplication::translate("MainWindow", "Res\303\255duo Incubat\303\263rio", nullptr));
        CmB_AmostraFase->setItemText(66, QCoreApplication::translate("MainWindow", "Res\303\255duo Org\303\242nico", nullptr));
        CmB_AmostraFase->setItemText(67, QCoreApplication::translate("MainWindow", "Res\303\255duo S\303\263lido Extrusora", nullptr));
        CmB_AmostraFase->setItemText(68, QCoreApplication::translate("MainWindow", "Res\303\255duos M\303\241quinas Limpeza de Gr\303\243os", nullptr));
        CmB_AmostraFase->setItemText(69, QCoreApplication::translate("MainWindow", "Res\303\255duoes Peneira", nullptr));
        CmB_AmostraFase->setItemText(70, QCoreApplication::translate("MainWindow", "Salv\303\255nia", nullptr));
        CmB_AmostraFase->setItemText(71, QCoreApplication::translate("MainWindow", "Sedimento", nullptr));
        CmB_AmostraFase->setItemText(72, QCoreApplication::translate("MainWindow", "Silagem de Aveia", nullptr));
        CmB_AmostraFase->setItemText(73, QCoreApplication::translate("MainWindow", "Silagem de Braqui\303\241ria", nullptr));
        CmB_AmostraFase->setItemText(74, QCoreApplication::translate("MainWindow", "Silagem de Grama", nullptr));
        CmB_AmostraFase->setItemText(75, QCoreApplication::translate("MainWindow", "Silagem de Grama  + Glicerina", nullptr));
        CmB_AmostraFase->setItemText(76, QCoreApplication::translate("MainWindow", "Res\303\255duo de Gr\303\243os", nullptr));
        CmB_AmostraFase->setItemText(77, QCoreApplication::translate("MainWindow", "Silagem de Milho", nullptr));
        CmB_AmostraFase->setItemText(78, QCoreApplication::translate("MainWindow", "Silagem de Trigo", nullptr));
        CmB_AmostraFase->setItemText(79, QCoreApplication::translate("MainWindow", "S\303\263lido", nullptr));
        CmB_AmostraFase->setItemText(80, QCoreApplication::translate("MainWindow", "S\303\263lido Extrusora", nullptr));
        CmB_AmostraFase->setItemText(81, QCoreApplication::translate("MainWindow", "Soro de Leite", nullptr));
        CmB_AmostraFase->setItemText(82, QCoreApplication::translate("MainWindow", "Tangencial", nullptr));
        CmB_AmostraFase->setItemText(83, QCoreApplication::translate("MainWindow", "Termina\303\247\303\243o", nullptr));
        CmB_AmostraFase->setItemText(84, QCoreApplication::translate("MainWindow", "Torta de Filtro", nullptr));
        CmB_AmostraFase->setItemText(85, QCoreApplication::translate("MainWindow", "Triturado de Madeira", nullptr));
        CmB_AmostraFase->setItemText(86, QCoreApplication::translate("MainWindow", "UPL", nullptr));
        CmB_AmostraFase->setItemText(87, QCoreApplication::translate("MainWindow", "Uruchloa Subquadripara", nullptr));
        CmB_AmostraFase->setItemText(88, QCoreApplication::translate("MainWindow", "Vinha\303\247a", nullptr));
        CmB_AmostraFase->setItemText(89, QCoreApplication::translate("MainWindow", "V\303\255sceras", nullptr));
        CmB_AmostraFase->setItemText(90, QCoreApplication::translate("MainWindow", "Wolffia", nullptr));
        CmB_AmostraFase->setItemText(91, QCoreApplication::translate("MainWindow", "Zebrina Trandescandia", nullptr));

        Lbl_Procedencia->setText(QCoreApplication::translate("MainWindow", "Proced\303\252ncia*", nullptr));
        CmB_Procedencia->setItemText(0, QCoreApplication::translate("MainWindow", "--Selecione--", nullptr));
        CmB_Procedencia->setItemText(1, QCoreApplication::translate("MainWindow", "Amafil Alimentos", nullptr));
        CmB_Procedencia->setItemText(2, QCoreApplication::translate("MainWindow", "Amidos Mundo Novo", nullptr));
        CmB_Procedencia->setItemText(3, QCoreApplication::translate("MainWindow", "Amitec (Goioer\303\252)", nullptr));
        CmB_Procedencia->setItemText(4, QCoreApplication::translate("MainWindow", "Agropecu\303\241ria Estrela da Manh\303\243 LTDA", nullptr));
        CmB_Procedencia->setItemText(5, QCoreApplication::translate("MainWindow", "Ajuricaba (Adriana Kunz (Delcia Osterkamp))", nullptr));
        CmB_Procedencia->setItemText(6, QCoreApplication::translate("MainWindow", "Ajuricaba (Ataides Hansen)", nullptr));
        CmB_Procedencia->setItemText(7, QCoreApplication::translate("MainWindow", "Ajuricaba (Carlos e Noeli Zahler)", nullptr));
        CmB_Procedencia->setItemText(8, QCoreApplication::translate("MainWindow", "Ajuricaba (David Dilkin)", nullptr));
        CmB_Procedencia->setItemText(9, QCoreApplication::translate("MainWindow", "Ajuricaba (Eldo Matte)", nullptr));
        CmB_Procedencia->setItemText(10, QCoreApplication::translate("MainWindow", "Ajuricaba (Elizabet Vargas)", nullptr));
        CmB_Procedencia->setItemText(11, QCoreApplication::translate("MainWindow", "Ajuricaba (Elmiro Berwald)", nullptr));
        CmB_Procedencia->setItemText(12, QCoreApplication::translate("MainWindow", "Ajuricaba (Eug\303\252nio e Reinoldo Wolfart)", nullptr));
        CmB_Procedencia->setItemText(13, QCoreApplication::translate("MainWindow", "Ajuricaba (Fernando F\303\255gula)", nullptr));
        CmB_Procedencia->setItemText(14, QCoreApplication::translate("MainWindow", "Ajuricaba (Hedo Allenbrandt)", nullptr));
        CmB_Procedencia->setItemText(15, QCoreApplication::translate("MainWindow", "Ajuricaba (Milton Layter)", nullptr));
        CmB_Procedencia->setItemText(16, QCoreApplication::translate("MainWindow", "Ajuricaba (Moacir Rupulo)", nullptr));
        CmB_Procedencia->setItemText(17, QCoreApplication::translate("MainWindow", "Ajuricaba (Maide Pinz)", nullptr));
        CmB_Procedencia->setItemText(18, QCoreApplication::translate("MainWindow", "Ajuricaba (Neiva Escher Kotters)", nullptr));
        CmB_Procedencia->setItemText(19, QCoreApplication::translate("MainWindow", "Ajuricaba (Odacir Rupolo)", nullptr));
        CmB_Procedencia->setItemText(20, QCoreApplication::translate("MainWindow", "Ajuricaba (Pedro Regelmeier e Usula Fritsch)", nullptr));
        CmB_Procedencia->setItemText(21, QCoreApplication::translate("MainWindow", "Ajuricaba (S\303\255rio S\303\251rgio Nath)", nullptr));
        CmB_Procedencia->setItemText(22, QCoreApplication::translate("MainWindow", "Ajuricaba (Teobaldo Neunfeld)", nullptr));
        CmB_Procedencia->setItemText(23, QCoreApplication::translate("MainWindow", "Ajuricaba (Valmor Ademir Escher)", nullptr));
        CmB_Procedencia->setItemText(24, QCoreApplication::translate("MainWindow", "Andr\303\251 Douglas", nullptr));
        CmB_Procedencia->setItemText(25, QCoreApplication::translate("MainWindow", "Andr\303\251 Amaral", nullptr));
        CmB_Procedencia->setItemText(26, QCoreApplication::translate("MainWindow", "Angelo Grigio", nullptr));
        CmB_Procedencia->setItemText(27, QCoreApplication::translate("MainWindow", "Apolo Energia", nullptr));
        CmB_Procedencia->setItemText(28, QCoreApplication::translate("MainWindow", "A.R.G", nullptr));
        CmB_Procedencia->setItemText(29, QCoreApplication::translate("MainWindow", "Barrac\303\243o de Aves", nullptr));
        CmB_Procedencia->setItemText(30, QCoreApplication::translate("MainWindow", "BSBIOS", nullptr));
        CmB_Procedencia->setItemText(31, QCoreApplication::translate("MainWindow", "Brazilian Oleochemical", nullptr));
        CmB_Procedencia->setItemText(32, QCoreApplication::translate("MainWindow", "C.Vale", nullptr));
        CmB_Procedencia->setItemText(33, QCoreApplication::translate("MainWindow", "Cana Brava", nullptr));
        CmB_Procedencia->setItemText(34, QCoreApplication::translate("MainWindow", "Caroliny Matinc", nullptr));
        CmB_Procedencia->setItemText(35, QCoreApplication::translate("MainWindow", "Cer\303\242mica Stein", nullptr));
        CmB_Procedencia->setItemText(36, QCoreApplication::translate("MainWindow", "CELF-Energias", nullptr));
        CmB_Procedencia->setItemText(37, QCoreApplication::translate("MainWindow", "Cocamar", nullptr));
        CmB_Procedencia->setItemText(38, QCoreApplication::translate("MainWindow", "Colombari", nullptr));
        CmB_Procedencia->setItemText(39, QCoreApplication::translate("MainWindow", "Cooke Aquaculture Chile", nullptr));
        CmB_Procedencia->setItemText(40, QCoreApplication::translate("MainWindow", "Ecocitrus", nullptr));
        CmB_Procedencia->setItemText(41, QCoreApplication::translate("MainWindow", "Eduardo Fontes Silveira", nullptr));
        CmB_Procedencia->setItemText(42, QCoreApplication::translate("MainWindow", "Eliana de Bona", nullptr));
        CmB_Procedencia->setItemText(43, QCoreApplication::translate("MainWindow", "Eliane Vendrusculo", nullptr));
        CmB_Procedencia->setItemText(44, QCoreApplication::translate("MainWindow", "Eliane Vendrusculo (Pedro Regelmeier)", nullptr));
        CmB_Procedencia->setItemText(45, QCoreApplication::translate("MainWindow", "ER-GP", nullptr));
        CmB_Procedencia->setItemText(46, QCoreApplication::translate("MainWindow", "EMBRAPA", nullptr));
        CmB_Procedencia->setItemText(47, QCoreApplication::translate("MainWindow", "ERO", nullptr));
        CmB_Procedencia->setItemText(48, QCoreApplication::translate("MainWindow", "Esta\303\247\303\243o Experimental Biovertis", nullptr));
        CmB_Procedencia->setItemText(49, QCoreApplication::translate("MainWindow", "Farinheira Guaipor\303\243", nullptr));
        CmB_Procedencia->setItemText(50, QCoreApplication::translate("MainWindow", "Fazenda Continental", nullptr));
        CmB_Procedencia->setItemText(51, QCoreApplication::translate("MainWindow", "FC Stone", nullptr));
        CmB_Procedencia->setItemText(52, QCoreApplication::translate("MainWindow", "Fecularia Bankhardt", nullptr));
        CmB_Procedencia->setItemText(53, QCoreApplication::translate("MainWindow", "Fecularia Lopes", nullptr));
        CmB_Procedencia->setItemText(54, QCoreApplication::translate("MainWindow", "Fecularia Podium", nullptr));
        CmB_Procedencia->setItemText(55, QCoreApplication::translate("MainWindow", "Fernando Langwiski", nullptr));
        CmB_Procedencia->setItemText(56, QCoreApplication::translate("MainWindow", "Generall Mills", nullptr));
        CmB_Procedencia->setItemText(57, QCoreApplication::translate("MainWindow", "Gon\303\247alves e Tortola AS (GT Foods)", nullptr));
        CmB_Procedencia->setItemText(58, QCoreApplication::translate("MainWindow", "Granja Cacic", nullptr));
        CmB_Procedencia->setItemText(59, QCoreApplication::translate("MainWindow", "Granja Haacke", nullptr));
        CmB_Procedencia->setItemText(60, QCoreApplication::translate("MainWindow", "General Water/ Granja Vianna", nullptr));
        CmB_Procedencia->setItemText(61, QCoreApplication::translate("MainWindow", "Grupo ARG", nullptr));
        CmB_Procedencia->setItemText(62, QCoreApplication::translate("MainWindow", "Horizonte", nullptr));
        CmB_Procedencia->setItemText(63, QCoreApplication::translate("MainWindow", "Laborat\303\263rio", nullptr));
        CmB_Procedencia->setItemText(64, QCoreApplication::translate("MainWindow", "Lacto", nullptr));
        CmB_Procedencia->setItemText(65, QCoreApplication::translate("MainWindow", "Latic\303\255nio Gua\303\255ra", nullptr));
        CmB_Procedencia->setItemText(66, QCoreApplication::translate("MainWindow", "Latic\303\255nio Latco", nullptr));
        CmB_Procedencia->setItemText(67, QCoreApplication::translate("MainWindow", "Leal Engenharia Quimica LTDA", nullptr));
        CmB_Procedencia->setItemText(68, QCoreApplication::translate("MainWindow", "Lucas F. J. Wessling", nullptr));
        CmB_Procedencia->setItemText(69, QCoreApplication::translate("MainWindow", "Luiz Hoffman", nullptr));
        CmB_Procedencia->setItemText(70, QCoreApplication::translate("MainWindow", "Interlaboratorial Embrapa", nullptr));
        CmB_Procedencia->setItemText(71, QCoreApplication::translate("MainWindow", "Industria de sucos  Prats", nullptr));
        CmB_Procedencia->setItemText(72, QCoreApplication::translate("MainWindow", "Itaipu", nullptr));
        CmB_Procedencia->setItemText(73, QCoreApplication::translate("MainWindow", "Lar", nullptr));
        CmB_Procedencia->setItemText(74, QCoreApplication::translate("MainWindow", "Mabel Alimentos", nullptr));
        CmB_Procedencia->setItemText(75, QCoreApplication::translate("MainWindow", "MAPA", nullptr));
        CmB_Procedencia->setItemText(76, QCoreApplication::translate("MainWindow", "Mar del Plata", nullptr));
        CmB_Procedencia->setItemText(77, QCoreApplication::translate("MainWindow", "Milton Layter", nullptr));
        CmB_Procedencia->setItemText(78, QCoreApplication::translate("MainWindow", "Nayareth", nullptr));
        CmB_Procedencia->setItemText(79, QCoreApplication::translate("MainWindow", "Nutriamidos", nullptr));
        CmB_Procedencia->setItemText(80, QCoreApplication::translate("MainWindow", "PAFE", nullptr));
        CmB_Procedencia->setItemText(81, QCoreApplication::translate("MainWindow", "Parque Nacional do Igua\303\247u", nullptr));
        CmB_Procedencia->setItemText(82, QCoreApplication::translate("MainWindow", "Pasquini Amidos", nullptr));
        CmB_Procedencia->setItemText(83, QCoreApplication::translate("MainWindow", "Paulo de Carvalho Mendes", nullptr));
        CmB_Procedencia->setItemText(84, QCoreApplication::translate("MainWindow", "Petropar", nullptr));
        CmB_Procedencia->setItemText(85, QCoreApplication::translate("MainWindow", "Podium Alimentos", nullptr));
        CmB_Procedencia->setItemText(86, QCoreApplication::translate("MainWindow", "Prof\302\252 Estela", nullptr));
        CmB_Procedencia->setItemText(87, QCoreApplication::translate("MainWindow", "Thiago Edwiges", nullptr));
        CmB_Procedencia->setItemText(88, QCoreApplication::translate("MainWindow", "Ra\303\255zen", nullptr));
        CmB_Procedencia->setItemText(89, QCoreApplication::translate("MainWindow", "Ref\303\272gio", nullptr));
        CmB_Procedencia->setItemText(90, QCoreApplication::translate("MainWindow", "Restaurante ", nullptr));
        CmB_Procedencia->setItemText(91, QCoreApplication::translate("MainWindow", "Ricardo Muller", nullptr));
        CmB_Procedencia->setItemText(92, QCoreApplication::translate("MainWindow", "Rodolfo", nullptr));
        CmB_Procedencia->setItemText(93, QCoreApplication::translate("MainWindow", "Sadia", nullptr));
        CmB_Procedencia->setItemText(94, QCoreApplication::translate("MainWindow", "Sagitta", nullptr));
        CmB_Procedencia->setItemText(95, QCoreApplication::translate("MainWindow", "Star Milk", nullptr));
        CmB_Procedencia->setItemText(96, QCoreApplication::translate("MainWindow", "Superbac", nullptr));
        CmB_Procedencia->setItemText(97, QCoreApplication::translate("MainWindow", "Tania Menegol", nullptr));
        CmB_Procedencia->setItemText(98, QCoreApplication::translate("MainWindow", "UD CIBiog\303\241s", nullptr));
        CmB_Procedencia->setItemText(99, QCoreApplication::translate("MainWindow", "Wegmed", nullptr));
        CmB_Procedencia->setItemText(100, QCoreApplication::translate("MainWindow", "WestRock", nullptr));

        groupBox->setTitle(QString());
        Btn_Salvar->setText(QCoreApplication::translate("MainWindow", "Salvar", nullptr));
        label_Obrigatorios->setText(QCoreApplication::translate("MainWindow", "Campos Obrigat\303\263rios (*)", nullptr));
        GrBox_Valores->setTitle(QString());
        Lbl_Biogas->setText(QCoreApplication::translate("MainWindow", "Biog\303\241s 1 (LNbiog\303\241s.kg sv\302\271)", nullptr));
        Edt_Biogas1->setText(QString());
        Edt_Biogas1->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Lbl_AmostraBiogas1->setText(QCoreApplication::translate("MainWindow", "Amostras", nullptr));
        Edt_Biogas2->setText(QString());
        Edt_Biogas2->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_Biogas3->setText(QString());
        Edt_Biogas3->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_Metano3->setText(QString());
        Edt_Metano3->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_Metano2->setText(QString());
        Edt_Metano2->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_Metano1->setText(QString());
        Edt_Metano1->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Lbl_Metano->setText(QCoreApplication::translate("MainWindow", "Metano 1 (LNbiog\303\241s.kg sv\302\271)", nullptr));
        Edt_ST1->setText(QString());
        Edt_ST1->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_ST2->setText(QString());
        Edt_ST2->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_ST3->setText(QString());
        Edt_ST3->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Lbl_ST->setText(QCoreApplication::translate("MainWindow", "ST 1 (%)", nullptr));
        Edt_SV3->setText(QString());
        Edt_SV3->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Lbl_SV1->setText(QCoreApplication::translate("MainWindow", "SV 1 (%)", nullptr));
        Edt_SV1->setText(QString());
        Edt_SV1->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_SV2->setText(QString());
        Edt_SV2->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_DQO3->setText(QString());
        Edt_DQO3->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_DQO2->setText(QString());
        Edt_DQO2->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_DQO1->setText(QString());
        Edt_DQO1->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Lbl_DQO->setText(QCoreApplication::translate("MainWindow", "DQO 1 (mg de O2/L) (%)", nullptr));
        Edt_pH3->setText(QString());
        Edt_pH3->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_pH1->setText(QString());
        Edt_pH1->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Edt_pH2->setText(QString());
        Edt_pH2->setPlaceholderText(QCoreApplication::translate("MainWindow", "0", nullptr));
        Lbl_pH->setText(QCoreApplication::translate("MainWindow", "pH 1", nullptr));
        Lbl_DQO_2->setText(QCoreApplication::translate("MainWindow", "DQO 2 (mg de O2/L) (%)", nullptr));
        Lbl_SV1_2->setText(QCoreApplication::translate("MainWindow", "SV 2 (%)", nullptr));
        Lbl_Metano_2->setText(QCoreApplication::translate("MainWindow", "Metano 2 (LNbiog\303\241s.kg sv\302\271)", nullptr));
        Lbl_ST_2->setText(QCoreApplication::translate("MainWindow", "ST 2 (%)", nullptr));
        Lbl_Biogas_2->setText(QCoreApplication::translate("MainWindow", "Biog\303\241s 2 (LNbiog\303\241s.kg sv\302\271)", nullptr));
        Lbl_pH_2->setText(QCoreApplication::translate("MainWindow", "pH 2", nullptr));
        Lbl_Metano_3->setText(QCoreApplication::translate("MainWindow", "Metano 3 (LNbiog\303\241s.kg sv\302\271)", nullptr));
        Lbl_SV1_3->setText(QCoreApplication::translate("MainWindow", "SV 3 (%)", nullptr));
        Lbl_DQO_3->setText(QCoreApplication::translate("MainWindow", "DQO 3 (mg de O2/L) (%)", nullptr));
        Lbl_ST_3->setText(QCoreApplication::translate("MainWindow", "ST 3 (%)", nullptr));
        Lbl_Biogas_3->setText(QCoreApplication::translate("MainWindow", "Biog\303\241s 3 (LNbiog\303\241s.kg sv\302\271)", nullptr));
        Lbl_pH_3->setText(QCoreApplication::translate("MainWindow", "pH 3", nullptr));
        menuArquivo->setTitle(QCoreApplication::translate("MainWindow", "Arquivo", nullptr));
        menuAjuda->setTitle(QCoreApplication::translate("MainWindow", "Ajuda", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
